### ISSUE TITLE
Pushing NuGet symbol packages to the public symbol NuGet server doesn't have any effect

### ISSUE THREAD

**Issue by CIPop** [SymbolSource/SymbolSource#9] opened 2018-07-11 18:43 UTC
1.	Without any key:

```
nuget push  Microsoft.Azure.Devices.1.16.0.symbols.nupkg -source https://nuget.smbsrc.net/
WARNING: No API Key was provided and no API Key could be found for the symbol server (https://nuget.smbsrc.net/). To save an API Key for a source use the 'setApiKey' command.
Pushing Microsoft.Azure.Devices.1.16.0.symbols.nupkg to the symbol server (https://nuget.smbsrc.net/)...
  PUT https://nuget.smbsrc.net/api/v2/package/
Please provide credentials for: https://nuget.smbsrc.net/
UserName: Cannot prompt for input in non-interactive mode.
  Unauthorized https://nuget.smbsrc.net/api/v2/package/ 1947ms
An error was encountered when fetching 'PUT https://nuget.smbsrc.net/'. The request will now be retried.
Response status code does not indicate success: 401 (Must authenticate).
  PUT https://nuget.smbsrc.net/api/v2/package/
  Unauthorized https://nuget.smbsrc.net/api/v2/package/ 479ms
An error was encountered when fetching 'PUT https://nuget.smbsrc.net/'. The request will now be retried.
Response status code does not indicate success: 401 (Must authenticate).
  PUT https://nuget.smbsrc.net/api/v2/package/
  Unauthorized https://nuget.smbsrc.net/api/v2/package/ 467ms
Response status code does not indicate success: 401 (Must authenticate).
```

2.	With the key I’ve used to push the production packages to NuGet.org:

```
S:\release\2018-6-20
nuget push Microsoft.Azure.Devices.Client.1.17.0.symbols.nupkg <ProdNuGETKey> -source https://nuget.smbsrc.net
Pushing Microsoft.Azure.Devices.Client.1.17.0.symbols.nupkg to 'https://nuget.smbsrc.net'...
  POST https://www.nuget.org/api/v2/package/create-verification-key/Microsoft.Azure.Devices.Client/1.17.0
  OK https://www.nuget.org/api/v2/package/create-verification-key/Microsoft.Azure.Devices.Client/1.17.0 590ms
  PUT https://nuget.smbsrc.net/api/v2/package/
  OK https://nuget.smbsrc.net/api/v2/package/ 3071ms
Your package was pushed.
```

I can run step 2 several times and it always succeeds. I was expecting that running it the second time would give me an error as the package was already uploaded.

Symbols still fail to load for our lib. All other symbols for the .NET Core load correctly:

```
Microsoft.Azure.Devices.Client.dll      Microsoft.Azure.Devices.Client.dll C:\Users\ZZZ\.nuget\packages\microsoft.azure.devices.client\1.17.0\lib\netstandard2.0\Microsoft.Azure.Devices.Client.dll       Yes    N/A    Cannot find or open the PDB file.       4      1.17.0.0     <Unknown>       0000022AE01B0000-0000022AE0256000 [160456] dotnet.exe [1] clrhost  
```

Symbol logs from Visual Studio:
```
C:\Program Files\dotnet\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
C:\Users\ZZZZZZ.ZZZZZZ\.nuget\packages\microsoft.azure.devices.client\1.17.0\lib\netstandard2.0\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
S:\azure-iot-sdk-csharp\iothub\device\src\obj\Release\netstandard2.0\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
C:\WINDOWS\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
C:\WINDOWS\symbols\dll\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
C:\WINDOWS\dll\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46bf0f5101794d4b9b79a68b6913d8d2ffffffff\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\MicrosoftPublicSymbols\Microsoft.Azure.Devices.Client.pdb\46bf0f5101794d4b9b79a68b6913d8d2ffffffff\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46bf0f5101794d4b9b79a68b6913d8d21\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\MicrosoftPublicSymbols\Microsoft.Azure.Devices.Client.pdb\46bf0f5101794d4b9b79a68b6913d8d21\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
SYMSRV:  BYINDEX: 0xD
         C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache*http://referencesource.microsoft.com/symbols
         Microsoft.Azure.Devices.Client.pdb
         46BF0F5101794D4B9B79A68B6913D8D2ffffffff


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pdb - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pd_ - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\file.ptr - path not found


SYMSRV:  HTTPGET: /symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pdb


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pd_


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/file.ptr


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  RESULT: 0x80190194


SYMSRV:  BYINDEX: 0xE
         C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache*http://referencesource.microsoft.com/symbols
         Microsoft.Azure.Devices.Client.pdb
         46BF0F5101794D4B9B79A68B6913D8D21


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\Microsoft.Azure.Devices.Client.pdb - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\Microsoft.Azure.Devices.Client.pd_ - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\file.ptr - path not found


SYMSRV:  HTTPGET: /symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/Microsoft.Azure.Devices.Client.pdb


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/Microsoft.Azure.Devices.Client.pd_


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/file.ptr


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  RESULT: 0x80190194


http://referencesource.microsoft.com/symbols: Symbols not found on symbol server.
SYMSRV:  BYINDEX: 0xF
         C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache*http://srv.symbolsource.org/pdb/Public
         Microsoft.Azure.Devices.Client.pdb
         46BF0F5101794D4B9B79A68B6913D8D2ffffffff


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pdb - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pd_ - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\file.ptr - path not found


SYMSRV:  HTTPGET: /pdb/Public/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pdb


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /pdb/Public/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pd_


SYMSRV:  HttpQueryInfo: 801900c8 - HTTP_STATUS_OK


SYMSRV:  Microsoft.Azure.Devices.Client.pdb from http://srv.symbolsource.org/pdb/Public: 0 bytes 

SYMSRV:  PATH: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pdb


SYMSRV:  RESULT: 0x00000000


http://srv.symbolsource.org/pdb/Public: Symbols downloaded from symbol server.
C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pdb: Cannot find or open the PDB file.
SYMSRV:  BYINDEX: 0x10
         C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache*http://srv.symbolsource.org/pdb/MyGet
         Microsoft.Azure.Devices.Client.pdb
         46BF0F5101794D4B9B79A68B6913D8D2ffffffff


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pdb - file not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pd_ - file not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\file.ptr - file not found


SYMSRV:  HTTPGET: /pdb/MyGet/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pdb


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /pdb/MyGet/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pd_


SYMSRV:  HttpQueryInfo: 801901f4 - HTTP_STATUS_SERVER_ERROR


SYMSRV:  RESULT: 0x801901F4


SYMSRV:  BYINDEX: 0x11
         C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache*http://srv.symbolsource.org/pdb/MyGet
         Microsoft.Azure.Devices.Client.pdb
         46BF0F5101794D4B9B79A68B6913D8D21


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\Microsoft.Azure.Devices.Client.pdb - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\Microsoft.Azure.Devices.Client.pd_ - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\file.ptr - path not found


SYMSRV:  HTTPGET: /pdb/MyGet/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/Microsoft.Azure.Devices.Client.pdb


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /pdb/MyGet/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/Microsoft.Azure.Devices.Client.pd_


SYMSRV:  HttpQueryInfo: 801901f4 - HTTP_STATUS_SERVER_ERROR


SYMSRV:  RESULT: 0x801901F4


http://srv.symbolsource.org/pdb/MyGet: Symbols not found on symbol server.
SYMSRV:  BYINDEX: 0x12
         C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache*http://msdl.microsoft.com/download/symbols
         Microsoft.Azure.Devices.Client.pdb
         46BF0F5101794D4B9B79A68B6913D8D2ffffffff


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pdb - file not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pd_ - file not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\file.ptr - file not found


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pdb


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pd_


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/file.ptr


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  RESULT: 0x80190194


SYMSRV:  BYINDEX: 0x13
         C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache*http://msdl.microsoft.com/download/symbols
         Microsoft.Azure.Devices.Client.pdb
         46BF0F5101794D4B9B79A68B6913D8D21


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\Microsoft.Azure.Devices.Client.pdb - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\Microsoft.Azure.Devices.Client.pd_ - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\file.ptr - path not found


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/Microsoft.Azure.Devices.Client.pdb


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/Microsoft.Azure.Devices.Client.pd_


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/file.ptr


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  RESULT: 0x80190194


http://msdl.microsoft.com/download/symbols: Symbols not found on symbol server.
SYMSRV:  BYINDEX: 0x14
         C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache*https://msdl.microsoft.com/download/symbols
         Microsoft.Azure.Devices.Client.pdb
         46BF0F5101794D4B9B79A68B6913D8D2ffffffff


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pdb - file not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\Microsoft.Azure.Devices.Client.pd_ - file not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D2ffffffff\file.ptr - file not found


SYMSRV:  HTTPGET: /download/symbols/index2.txt


SYMSRV:  HttpQueryInfo: 80190190 - HTTP_STATUS_BAD_REQUEST


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pdb


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/Microsoft.Azure.Devices.Client.pd_


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D2ffffffff/file.ptr


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  RESULT: 0x80190194


SYMSRV:  BYINDEX: 0x15
         C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache*https://msdl.microsoft.com/download/symbols
         Microsoft.Azure.Devices.Client.pdb
         46BF0F5101794D4B9B79A68B6913D8D21


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\Microsoft.Azure.Devices.Client.pdb - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\Microsoft.Azure.Devices.Client.pd_ - path not found


SYMSRV:  UNC: C:\Users\ZZZZZZ\AppData\Local\Temp\SymbolCache\Microsoft.Azure.Devices.Client.pdb\46BF0F5101794D4B9B79A68B6913D8D21\file.ptr - path not found


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/Microsoft.Azure.Devices.Client.pdb


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/Microsoft.Azure.Devices.Client.pd_


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  HTTPGET: /download/symbols/Microsoft.Azure.Devices.Client.pdb/46BF0F5101794D4B9B79A68B6913D8D21/file.ptr


SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND


SYMSRV:  RESULT: 0x80190194


https://msdl.microsoft.com/download/symbols: Symbols not found on symbol server.
```

**Comment by TripleEmcoder** [comment] 2018-07-17 19:22
Since you mentioned .NET Core I am assuming this is because of the lack of Portable PDB support in the current code, and marking this as a duplicate of #7 .

Now to explain the submission behavior - since PDB indexing takes some time, it is done entirely asynchronously by the processing backend, therefore any submission succeeds with nuget.exe as long as data gets through the wire. You can however subscribe to notifications, but only via Twitter at the moment, by adding a slash and your Twitter handle, e.g.:

`nuget push SymbolSource.DemoLibrary-1.0.0.0.nupkg a0f4e24d-851f-4327-a9ec-181d335e7e95/@TripleEmcoder -source https://nuget.smbsrc.net`

**Comment by TripleEmcoder** [comment] 2018-07-17 19:25
Lets try linking again: duplicate of #7.

**Comment by TripleEmcoder** [comment] 2018-07-17 19:26
Marking as duplicate of #7

**Comment by CIPop** [comment] 2018-07-18 17:27
> Since you mentioned .NET Core I am assuming this is because of the lack of Portable PDB support in the current code, and marking this as a duplicate of #7 .

@TripleEmcoder my understanding is that dotnet core produces [Portable PDBs by default](https://github.com/OmniSharp/omnisharp-vscode/wiki/Portable-PDBs#csproj). I have the files - how would one check if this is true?

>> With .NET Core projects .csproj's (the new type of project supported by VS 2017 or .NET CLI preview 3 or newer), Portable PDBs are already enabled by default.

**Comment by CIPop** [comment] 2018-08-18 02:11
@TripleEmcoder any updates? Is there any way to publish NuGet Symbol packages at this moment?

**Comment by TripleEmcoder** [comment] 2018-09-05 10:05
What I can only suggest is that you switch to `DebugType=Full` if possible. Support in #7 still needs to happen.

**Closed as completed by TripleEmcoder** 2018-09-05 10:05 UTC
Labels: duplicate
